// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: role.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DomainRole with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DomainRole) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DomainRole with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DomainRoleMultiError, or
// nil if none found.
func (m *DomainRole) ValidateAll() error {
	return m.validate(true)
}

func (m *DomainRole) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_DomainRole_DomainName_Pattern.MatchString(m.GetDomainName()) {
		err := DomainRoleValidationError{
			field:  "DomainName",
			reason: "value does not match regex pattern \"^[0-9a-zA-Z_]{1,}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for RoleName

	if len(errors) > 0 {
		return DomainRoleMultiError(errors)
	}

	return nil
}

// DomainRoleMultiError is an error wrapping multiple validation errors
// returned by DomainRole.ValidateAll() if the designated constraints aren't met.
type DomainRoleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DomainRoleMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DomainRoleMultiError) AllErrors() []error { return m }

// DomainRoleValidationError is the validation error returned by
// DomainRole.Validate if the designated constraints aren't met.
type DomainRoleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DomainRoleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DomainRoleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DomainRoleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DomainRoleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DomainRoleValidationError) ErrorName() string { return "DomainRoleValidationError" }

// Error satisfies the builtin error interface
func (e DomainRoleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDomainRole.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DomainRoleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DomainRoleValidationError{}

var _DomainRole_DomainName_Pattern = regexp.MustCompile("^[0-9a-zA-Z_]{1,}$")

// Validate checks the field values on AddDomainRoleRpl with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddDomainRoleRpl) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddDomainRoleRpl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddDomainRoleRplMultiError, or nil if none found.
func (m *AddDomainRoleRpl) ValidateAll() error {
	return m.validate(true)
}

func (m *AddDomainRoleRpl) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetCreatTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddDomainRoleRplValidationError{
					field:  "CreatTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddDomainRoleRplValidationError{
					field:  "CreatTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddDomainRoleRplValidationError{
				field:  "CreatTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Name

	// no validation rules for Domain

	if len(errors) > 0 {
		return AddDomainRoleRplMultiError(errors)
	}

	return nil
}

// AddDomainRoleRplMultiError is an error wrapping multiple validation errors
// returned by AddDomainRoleRpl.ValidateAll() if the designated constraints
// aren't met.
type AddDomainRoleRplMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddDomainRoleRplMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddDomainRoleRplMultiError) AllErrors() []error { return m }

// AddDomainRoleRplValidationError is the validation error returned by
// AddDomainRoleRpl.Validate if the designated constraints aren't met.
type AddDomainRoleRplValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddDomainRoleRplValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddDomainRoleRplValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddDomainRoleRplValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddDomainRoleRplValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddDomainRoleRplValidationError) ErrorName() string { return "AddDomainRoleRplValidationError" }

// Error satisfies the builtin error interface
func (e AddDomainRoleRplValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddDomainRoleRpl.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddDomainRoleRplValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddDomainRoleRplValidationError{}
